AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Cloud Formation Deployment"

Parameters:
  S3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: test-bucket-cloudformations
    Type: String
  S3BucketKey:
    AllowedPattern: ^[a-zA-Z0-9_./]*$
    Default: deploy.zip
    Type: String

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Sub '${S3BucketName}'
        S3Key: !Sub '${QSS3KeyPrefix}/${S3BucketKey}'
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt "SampleLambdaRole.Arn"
      Runtime: python3.7

  Lambda2:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Sub '${S3BucketName}'
        S3Key: !Sub '${QSS3KeyPrefix}/${S3BucketKey}'
      Handler: "lambda_function2.lambda_handler"
      Role: !GetAtt "SampleLambdaRole.Arn"
      Runtime: python3.7
    
  SampleLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: "Allow"
            Principal:
              Service: ["lambda.amazonaws.com"]
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: ["cloudwatch:*", "logs:*"]
                Effect: "Allow"
                Resource: "*"
          PolicyName: "lambdaLogPolicy"
