AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Cloud Formation Deployment"

Parameters:
  S3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: test-bucket-cloudformations
    Type: String
    NoEcho: True
  S3BucketKey:
    AllowedPattern: ^[a-zA-Z0-9_./]*$
    Default: deploy.zip
    Type: String
    NoEcho: True
  ENVname:
    AllowedPattern: ^[a-zA-Z0-9_./]*$
    Default: MY_VALUE
    Type: String
    NoEcho: True
  ENVexample:
    AllowedPattern: ^[a-zA-Z0-9_./]*$
    Default: MY_ENV
    Type: String
    NoEcho: True
  apiGatewayStageName: 
    Type: String
    Default: "dev"
    AllowedValues: 
      - dev
      - staging
      - prod
    Description: Enter dev, staging, prod.

Resources:
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "example-api-gw"
      Description: "Example API"

  ProxyResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt apiGateway.RootResourceId
      RestApiId: !Ref apiGateway

  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        IntegrationResponses:
          -
            StatusCode: 200
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "Lambda1.Arn"
      ResourceId: !Ref ProxyResource
      RestApiId: !Ref "apiGateway"


  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "apiGateway"
      StageName: !Ref "apiGatewayStageName"

  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: LambdaOne
      Code: src/
      Description: "Code Description 1"
      Handler: "lambdas/lambda_function.lambda_handler"
      Role: !GetAtt "SampleLambdaRole.Arn"
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          MY_ENV: !Sub ${ENVexample}

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt [ Lambda1, Arn ]
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*


  # Lambda2:
  #   Type: "AWS::Lambda::Function"
  #   Properties:
  #     FunctionName: LambdaTwo
  #     Code: src/
  #     Description: "Code Description 2"
  #     Handler: "lambdas/lambda_function2.lambda_handler"
  #     Role: !GetAtt "SampleLambdaRole.Arn"
  #     Runtime: python3.7
  #     MemorySize: 128
  #     Timeout: 60

  # Gateway2:
  #   Type: 'AWS::ApiGateway::RestApi'
  #   DependsOn: Lambda2
  #   Properties:
  #     Name: Gateway-Lambda2
  #     Description: Lambda HTTP Gateway Proxy
  #     Target: !GetAtt [ Lambda2, Arn ]
  #     ProtocolType: "HTTP"

  # LambdaApiGatewayPermission2:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !GetAtt [ Lambda2, Arn ]
  #     Principal: apigateway.amazonaws.com
  #     SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Gateway2}/*


  # MySecret:
  #   Type: 'AWS::SecretsManager::Secret'
  #   Properties:
  #     Name: MySecret
  #     Description: This should create a secret
  #     SecretString: !sub ${ENVname}


  SampleLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: "Allow"
            Principal:
              Service: ["lambda.amazonaws.com"]
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: ["cloudwatch:*", 
                "logs:*",                 
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecrets"]
                Effect: "Allow"
                Resource: "*"
          PolicyName: "lambdaLogPolicy"
