AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Secrets Mangaer"

Parameters:
  ENVname:
    AllowedPattern: ^[a-zA-Z0-9_./]*$
    Default: MY_VALUE
    Type: String
    NoEcho: True

Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecret
      Description: This should create a secret
      SecretString: !sub ${ENVname}


