name: Code-Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature/**]

concurrency:
  group: auto-deploy-services

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd src/
        python3 -m pip install --upgrade pip
        pip3 install -r ../requirements.txt
        pip install -e .
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd src/
          pip3 install -r ../requirements.txt
          pip install -e .
      - name: Run test suite
        run: |          
          pytest src/

  auto-deploy-services:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint, test]
    # if: github.ref == 'refs/heads/main'
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Install pip
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd src/
          pip3 install -r ../requirements.txt
          pip install -e .
          cd ..

      - name: Deploy
        run: |
          rm -r src/tests
          aws cloudformation package \
          --template-file cloud-formation.yaml \
          --s3-bucket ${{secrets.AWS_S3_BUCKET}} \
          --s3-prefix deploy \
          --output-template-file deploy.yaml

          aws cloudformation validate-template \
            --template-body file://deploy.yaml

          aws cloudformation deploy \
          --template-file deploy.yaml \
          --stack-name Databricks-IR-Framework \
          --region us-west-1 \
          --capabilities CAPABILITY_IAM
   